### ISSUE TITLE
hmm

### ISSUE THREAD

**Issue by callowaylc** [jackdcasey/uup#1]
Hey, I saw that you had promoted your own tool, as an answer on stackoverflow, and I always try to make an effort to critique those instances, where possible. 

So first, there are already quite a few tcp/ping, the simplest of which is  `nc` or `telnet` in a loop; also tcp provides for guarantee/acknowledgement of delivery, which makes tcp+ping redundant, because a successful tcp connection is the same idea as a "ping/pong". You're also making the assumption that cli tools are only used in an interactive shell, and that the notifications of event state (up, down) are received by a human, where red/green holds meaning, but are impractical elsewhere and go no further than the terminal/tty device. 

The vast majority of the time that I am querying an up/down state, its being run from a non-interactive shell process,
like a readiness/availability probe, where exit status is used as a stateless, boolean check of availability. 
```
$ cat /tmp/manifest.yaml | grep -A5 -- livenessProbe
    livenessProbe:
      exec:
        command:
        - /tmp/probe.sh 
        - ${host}
        - ${port}
```
```sh
$ cat /tmp/probe.sh 
#!/bin/sh
set -eu

nc -z $1 $2 >/dev/null
```
Probe succeeds with exit status 0 when 3030 is available, and fails otherwise.
```sh 
$ ( nc -l 3030 & )
$ /tmp/probe.sh localhost 3030
$ echo $?
0
$ /tmp/probe.sh localhost 3030
$ echo $?
1
```

Or, we can use check as a means to block execution until some resource is available. 
```sh
 $ cat /tmp/test.sh 
#!/bin/bash
set -eu

logger -sp DEBUG "Provision resource" -- "seconds=$SECONDS"
sleep 5 && nc -l 3030 & # simulate provisioning of service that listens on port 3030

# block until port is available
logger -sp DEBUG "Block until available" -- "seconds=$SECONDS"
</dev/null watch -te  -- "! nc -z localhost 3030" &>/dev/null ||:

# continue orchestration once resource is ready
logger -sp DEBUG "Provisioned resource available" -- "seconds=$SECONDS"
```
```sh
$ /tmp/test.sh 
Dec  2 16:20:27  christian[32428] <Debug>: Provision resource -- seconds=0
Dec  2 16:20:27  christian[32430] <Debug>: Block until available -- seconds=0
Dec  2 16:20:33  christian[32452] <Debug>: Provisioned resource available -- seconds=6
```
 
You script doesn't seem to provide any programmatic hooks, or exit with a status that indicates availability, which means it can't be used by any downstream process and/or logical flow to make decisions based on previous availability check; that means its only use is as a green/red notification system for a human operator. 

If you refactor, can you write success/failure message STDERR, and use whatever swift's logger is, which among many things, will timestamp entries, allowing you to determine the state of a system, at a fixed point in time.

**Comment by jackdcasey** [comment]
These are very good points, I appreciate the feedback! 

Originally, I wrote this to keep an eye on a server while getting coffee, etc 😄. In that scenario, my priority was the simple coloured output for my human eyes. However, it makes heaps of sense to add exit values that correspond with the result of the testing. 

I'll look at adding that functionality! Thanks!

**Comment by callowaylc** [comment]
Dude, your positivity just made my day, so thank you for that.

**Comment by jackdcasey** [comment]
@callowaylc Just made those changes and will update the homebrew package soon. Thanks again for the suggestion! 

Please don't hesitate if you have any more 😄
